### ISSUE TITLE
Tooltip.js Error

### ISSUE THREAD

**Issue by voidsailor** [danielwalke/MPA_Pathway_Tool#4]
In "add user defined reaction", clicking on "switch" results in crash of the webpage. 

First line of Error message:

Uncaught TypeError: Cannot read properties of undefined (reading 'className')
    at Tooltip (Tooltip.js:453)

**Comment by voidsailor** [comment]
Same thing happens, when clicking on "Submit" in "Split Nodes"

**Comment by danielwalke** [comment]
thanks for reporting the issue. It should be fixed now.
